# Generated by Django 4.2.3 on 2023-07-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='url_to_path',
            new_name='url_or_path',
        ),
    ]
