# Generated by Django 4.2.3 on 2023-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_sitesetup_footer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='footer_link',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
